package com.example.util

import android.content.Context
import android.content.Intent
import android.graphics.Bitmap
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.RectF
import android.graphics.Typeface
import android.net.Uri
import android.widget.Toast
import androidx.core.content.FileProvider
import com.example.data.model.Bill
import java.io.File
import java.io.FileOutputStream

object ShareReceiptUtil {

    fun shareBillAsPhoto(context: Context, bill: Bill) {
        try {
            val bitmap = createReceiptBitmap(bill)
            val cachePath = File(context.cacheDir, "images")
            cachePath.mkdirs()
            val file = File(cachePath, "bill_${bill.billNumber}_${System.currentTimeMillis()}.png")
            val stream = FileOutputStream(file)
            bitmap.compress(Bitmap.CompressFormat.PNG, 100, stream)
            stream.close()

            val contentUri: Uri = FileProvider.getUriForFile(
                context,
                "${context.packageName}.fileprovider",
                file
            )

            val shareIntent = Intent(Intent.ACTION_SEND).apply {
                type = "image/png"
                putExtra(Intent.EXTRA_STREAM, contentUri)
                putExtra(
                    Intent.EXTRA_TEXT,
                    "APMC બિલ નં: ${bill.billNumber} | ${bill.shopName} | તારીખ: ${bill.date}"
                )
                addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
            }
            context.startActivity(Intent.createChooser(shareIntent, "બિલ ફોટો શેર કરો"))
        } catch (e: Exception) {
            e.printStackTrace()
            Toast.makeText(context, "ફોટો શેર કરવામાં ક્ષતિ: ${e.message}", Toast.LENGTH_SHORT).show()
        }
    }

    fun shareBillAsText(context: Context, bill: Bill) {
        val text = buildString {
            appendLine("📋 *APMC મજૂરી બિલ પાવતી*")
            appendLine("━━━━━━━━━━━━━━━━━━━")
            appendLine("📅 તારીખ: ${bill.date}")
            appendLine("🔢 બિલ નં: ${bill.billNumber}")
            if (bill.vakal.isNotEmpty()) appendLine("🏷️ વકલ: ${bill.vakal}")
            appendLine("🏪 દુકાન નં: ${bill.shopNumber}")
            appendLine("🏢 દુકાન: ${bill.shopName}")
            if (bill.shopMobile.isNotEmpty()) appendLine("📞 મોબાઇલ: ${bill.shopMobile}")
            appendLine("━━━━━━━━━━━━━━━━━━━")
            appendLine("📦 *માલ / ગણતરી:*")
            appendLine("• કટા (બારદાન): ${bill.kata}")
            appendLine("• ભરતી: ${bill.bharti} કિલો")
            if (bill.kilo > 0 || bill.gram > 0) {
                appendLine("• વધારાનું વજન: ${bill.kilo} કિલો ${bill.gram} ગ્રામ")
            }
            if (bill.shedNumber.isNotEmpty()) appendLine("• શેડ નં: ${bill.shedNumber}")
            if (bill.pillarNumber.isNotEmpty()) appendLine("• પીલોર નં: ${bill.pillarNumber}")
            if (bill.totalMudda.isNotEmpty()) appendLine("• કુલ મુદ્દા: ${bill.totalMudda}")
            appendLine("• ભાવ (દર): ₹${bill.bhav}")
            appendLine("━━━━━━━━━━━━━━━━━━━")
            appendLine("⚖️ *કુલ વજન: ${bill.totalWeight} કિલો*")
            appendLine("💰 *કુલ રકમ (Total): ₹${bill.totalAmount}*")
            appendLine("━━━━━━━━━━━━━━━━━━━")
            appendLine("Generated by Labour Bill App")
        }

        val shareIntent = Intent(Intent.ACTION_SEND).apply {
            type = "text/plain"
            putExtra(Intent.EXTRA_SUBJECT, "APMC બિલ પાવતી: ${bill.billNumber}")
            putExtra(Intent.EXTRA_TEXT, text)
        }
        context.startActivity(Intent.createChooser(shareIntent, "બિલ શેર કરો"))
    }

    private fun createReceiptBitmap(bill: Bill): Bitmap {
        val width = 800
        val height = 1100
        val bitmap = Bitmap.createBitmap(width, height, Bitmap.Config.ARGB_8888)
        val canvas = Canvas(bitmap)

        // Background
        canvas.drawColor(Color.WHITE)

        val borderPaint = Paint().apply {
            color = Color.parseColor("#1E3A8A")
            style = Paint.Style.STROKE
            strokeWidth = 6f
            isAntiAlias = true
        }
        canvas.drawRoundRect(RectF(24f, 24f, width - 24f, height - 24f), 24f, 24f, borderPaint)

        // Header Banner
        val headerPaint = Paint().apply {
            color = Color.parseColor("#1E3A8A")
            style = Paint.Style.FILL
            isAntiAlias = true
        }
        canvas.drawRoundRect(RectF(24f, 24f, width - 24f, 150f), 24f, 24f, headerPaint)
        canvas.drawRect(RectF(24f, 100f, width - 24f, 150f), headerPaint)

        val titlePaint = Paint().apply {
            color = Color.WHITE
            textSize = 42f
            isFakeBoldText = true
            isAntiAlias = true
            textAlign = Paint.Align.CENTER
        }
        canvas.drawText("APMC મજૂરી બિલ પાવતી", width / 2f, 90f, titlePaint)

        val subTitlePaint = Paint().apply {
            color = Color.parseColor("#E0E7FF")
            textSize = 24f
            isAntiAlias = true
            textAlign = Paint.Align.CENTER
        }
        canvas.drawText("Labour Bill Slip", width / 2f, 130f, subTitlePaint)

        // Shop box
        val shopBoxPaint = Paint().apply {
            color = Color.parseColor("#F1F5F9")
            style = Paint.Style.FILL
            isAntiAlias = true
        }
        canvas.drawRoundRect(RectF(50f, 175f, width - 50f, 310f), 16f, 16f, shopBoxPaint)

        val labelPaint = Paint().apply {
            color = Color.parseColor("#475569")
            textSize = 24f
            isAntiAlias = true
        }
        val boldValuePaint = Paint().apply {
            color = Color.parseColor("#0F172A")
            textSize = 28f
            isFakeBoldText = true
            isAntiAlias = true
        }

        var yPos = 215f
        canvas.drawText("દુકાન નંબર: ${bill.shopNumber}", 70f, yPos, boldValuePaint)
        canvas.drawText("તારીખ: ${bill.date}", width - 300f, yPos, boldValuePaint)

        yPos += 45f
        val shopText = if (bill.shopName.isNotEmpty()) bill.shopName else "અજય ટ્રેડર્સ"
        canvas.drawText("નામ: $shopText", 70f, yPos, boldValuePaint)

        yPos += 40f
        val mobileText = if (bill.shopMobile.isNotEmpty()) bill.shopMobile else "-"
        canvas.drawText("મોબાઇલ: $mobileText", 70f, yPos, labelPaint)
        canvas.drawText("બિલ નં: ${bill.billNumber}", width - 300f, yPos, boldValuePaint)

        // Divider
        val linePaint = Paint().apply {
            color = Color.parseColor("#CBD5E1")
            strokeWidth = 2f
        }
        yPos = 340f
        canvas.drawLine(50f, yPos, width - 50f, yPos, linePaint)

        // Goods Grid Header
        yPos += 40f
        val sectionTitlePaint = Paint().apply {
            color = Color.parseColor("#1E3A8A")
            textSize = 30f
            isFakeBoldText = true
            isAntiAlias = true
        }
        canvas.drawText("📦 માલ / ગણતરી વિગત", 50f, yPos, sectionTitlePaint)

        yPos += 50f
        val rows = listOf(
            "વકલ (Lot / Category)" to bill.vakal.ifEmpty { "-" },
            "કટા (Bags / Kata)" to "${bill.kata}",
            "ભરતી (Bharti / Bag)" to "${bill.bharti} kg",
            "કિલો (Kilo)" to "${bill.kilo} kg",
            "ગ્રામ (Gram)" to "${bill.gram} gm",
            "શેડ નંબર (Shed No.)" to bill.shedNumber.ifEmpty { "-" },
            "પીલોર નંબર (Pillar No.)" to bill.pillarNumber.ifEmpty { "-" },
            "કુલ મુદ્દા (Mudda)" to bill.totalMudda.ifEmpty { "-" },
            "ભાવ (Rate / Price)" to "₹ ${bill.bhav}"
        )

        for ((label, value) in rows) {
            canvas.drawText(label, 60f, yPos, labelPaint)
            val vPaint = Paint().apply {
                color = Color.parseColor("#1E293B")
                textSize = 26f
                isFakeBoldText = true
                isAntiAlias = true
                textAlign = Paint.Align.RIGHT
            }
            canvas.drawText(value, width - 60f, yPos, vPaint)
            yPos += 42f
        }

        // Total Box
        yPos += 20f
        val totalBoxPaint = Paint().apply {
            color = Color.parseColor("#0F172A")
            style = Paint.Style.FILL
            isAntiAlias = true
        }
        canvas.drawRoundRect(RectF(50f, yPos, width - 50f, yPos + 120f), 16f, 16f, totalBoxPaint)

        val totalLabelPaint = Paint().apply {
            color = Color.parseColor("#94A3B8")
            textSize = 24f
            isAntiAlias = true
        }
        val totalAmountPaint = Paint().apply {
            color = Color.WHITE
            textSize = 44f
            isFakeBoldText = true
            isAntiAlias = true
            textAlign = Paint.Align.RIGHT
        }
        val weightLabelPaint = Paint().apply {
            color = Color.parseColor("#38BDF8")
            textSize = 26f
            isFakeBoldText = true
            isAntiAlias = true
        }

        canvas.drawText("કુલ વજન: ${bill.totalWeight} kg", 80f, yPos + 50f, weightLabelPaint)
        canvas.drawText("કુલ રકમ (TOTAL)", 80f, yPos + 95f, totalLabelPaint)
        canvas.drawText("₹ ${bill.totalAmount}", width - 80f, yPos + 85f, totalAmountPaint)

        // Footer
        val footerPaint = Paint().apply {
            color = Color.parseColor("#64748B")
            textSize = 20f
            isAntiAlias = true
            textAlign = Paint.Align.CENTER
        }
        canvas.drawText("Labour Bill Application - APMC Market Edition", width / 2f, height - 50f, footerPaint)

        return bitmap
    }
}
