name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '9.3.1'

      - name: Make Gradle Wrapper Executable
        # આ કમાન્ડ આખા પ્રોજેક્ટમાં જ્યાં પણ gradlew હશે તેને શોધીને રન થવાની પરમિશન આપી દેશે
        run: |
          GRADLEW_PATH=$(find . -name gradlew -print -quit)
          if [ -z "$GRADLEW_PATH" ]; then
            echo "Error: gradlew not found!" && exit 1
          fi
          chmod +x "$GRADLEW_PATH"

      - name: Build APK
        # આ કમાન્ડ આપોઆપ સાચા ફોલ્ડરમાં જઈને એપ બિલ્ડ કરી નાખશે
        run: |
          GRADLEW_PATH=$(find . -name gradlew -print -quit)
          DIR_PATH=$(dirname "$GRADLEW_PATH")
          cd "$DIR_PATH" && ./gradlew assembleDebug

      - name: Check APK
        run: |
          echo "APK files:"
          find . -type f -name "*.apk" -print

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: APMC-Junagadh-APK
          # આ પાથ પ્રોજેક્ટમાં ગમે ત્યાં બનેલી APK ફાઇલને શોધીને અપલોડ કરી દેશે
          path: "**/build/outputs/apk/debug/*.apk"
          if-no-files-found: error
          
